build_image:
  image: tmaier/docker-compose:latest
  services:
  - docker:19.03.5-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker-compose build
    - docker-compose push
  only:
    - tags
    - master
